# Generated by Django 5.0.8 on 2024-08-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("project_link", models.URLField(verbose_name="Project Link")),
                (
                    "project_description",
                    models.TextField(verbose_name="Project Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Registration Request",
                "verbose_name_plural": "Merchant Registration Requests",
            },
        ),
    ]
